### ISSUE TITLE
Quest The Zhevra

### ISSUE THREAD

**Issue by MadeinNoxus** [SallyWhitemane/Maelstrom#55] opened 2022-06-06 15:12 UTC
**Description:**
Zhevra doesn't drop Zhevra Hooves

**How to reproduce:**
Kill Zhevra with the quest The Zhevra 
 
**How it should work:**
https://www.youtube.com/watch?v=OgxzAUd-9Ok&ab_channel=GitGudGuides

**Comment by ghost** [comment] 2022-06-06 15:18
Duplicate of #12

**Closed as completed by ghost** 2022-06-06 15:18 UTC
