### ISSUE TITLE
[NPC] Agrro issues with Arcane Wraith/Arcane Patroller 

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#185] opened 2022-06-17 12:59 UTC
**Description:** Some of the Arcane Wraith/Arcane Patroller  NPCS have agrro issues they wont attack players at all

**How to reproduce:**
some of them (specially the ones that patrol the area) wont attack the player and just fill their HP they wont react at all

**How it should work:** they should attack players and engage in combat with them 

![image](https://user-images.githubusercontent.com/36106057/174297404-6137f2ca-c4c1-4307-b124-07ace4d20030.png)
![image](https://user-images.githubusercontent.com/36106057/174302693-e6b840e4-1322-4906-81c5-235c64cd4f70.png)
![image](https://user-images.githubusercontent.com/36106057/174302792-b5c28ec1-1c5a-4e32-bae6-2ec14ab4db47.png)
![image](https://user-images.githubusercontent.com/36106057/174302917-413bd9ce-6042-4d46-bb9b-1b703a46772e.png)

**Comment by ghost** [comment] 2022-06-17 19:52
Duplicate of #118. Already fixed - not live yet.

**Closed as completed by ghost** 2022-06-17 19:52 UTC
