### ISSUE TITLE
Objects that can be mounted, bugged

### ISSUE THREAD

**Issue by ElFuegoBaby** [SallyWhitemane/Maelstrom#139] opened 2022-06-15 14:26 UTC
**Description:** If you ride an "object" and dismount after, you remain in air
tested yesterday with raptor from troll starting area, tested today in Deadmines

**How to reproduce:**
Ride a "object" from dungeon or quest then dismount

**How it should work:**
After you dismount, you need to be on the ground xD

**Comment by ghost** [comment] 2022-06-16 19:03
Duplicate of #123

**Closed as completed by ghost** 2022-06-16 19:03 UTC
