### ISSUE TITLE
[Quest] Val'kyr incursion

### ISSUE THREAD

**Issue by Craxzycubu** [SallyWhitemane/Maelstrom#172] opened 2022-06-16 23:15 UTC
**Description:**
Val'kyr's doesnt spawn in the area.

**How to reproduce:**
accept the Val'kyr incursion quest in andorhal. 

**How it should work:**
They should be in the area.

**Comment by phonkala** [comment] 2022-06-17 00:09
Duplicate of https://github.com/SallyWhitemane/Maelstrom/issues/117 . That one was closed so I believe it's fixed whenever next update becomes live on PTR.

**Comment by ghost** [comment] 2022-06-17 19:12
Yep.

**Closed as completed by ghost** 2022-06-17 19:12 UTC
