### ISSUE TITLE
[NPC] Lien Farner - Talk options are swaped!

### ISSUE THREAD

**Issue by Hewlith** [SallyWhitemane/Maelstrom#50] opened 2022-06-06 11:44 UTC
**Description:**
If you press "Tell me about gathering Professions" it shows Produktion Professions and the other way around.

**How to reproduce:**
Talk to Lien Farner and use one of the Talking Options.

**How it should work:**
The other way around :D

**Comment by phonkala** [comment] 2022-06-06 13:09
Duplicate of https://github.com/SallyWhitemane/Maelstrom/issues/23

**Closed as completed** 2022-06-07 10:40 UTC
