### ISSUE TITLE
Pygmy Surf Crawler infinite regeneration

### ISSUE THREAD

**Issue by Rebloc95** [SallyWhitemane/Maelstrom#3] opened 2022-06-03 17:23 UTC
**Description:**
Pygmy Surf Crawler in the troll starting zone have infinite regeneration. Also when this occurs, they don't attack back, they just run around doing nothing.

**How to reproduce:**
attack any of the swimming crabs in the trolls starting area

**How it should work:**
they should attack back and have no combat regeneration

![image](https://user-images.githubusercontent.com/106832561/171914704-f383df2b-642a-4f1e-b8ed-a1a42c8d4905.png)

**Comment by bovanova1** [comment] 2022-06-03 18:19
Is this supposed to be a critter too ?

**Comment by ghost** [comment] 2022-06-06 09:16
@Rebloc95 @bovanova1 I can't reproduce it.

**Comment by phonkala** [comment] 2022-06-06 12:41
Seems to be same issue than the other similar ones: mob getting bugged, not attacking and healing back to full non-stop. Those issues are now closed so I assume this will be fixed too when they are.

**Comment by ghost** [comment] 2022-06-06 13:25
And those issues were linked to stealth and I don't see here any connection with it.

**Comment by phonkala** [comment] 2022-06-06 13:46
@UltraNix 
> And those issues were linked to stealth and I don't see here any connection with it.

I believe autoattacking from stealth was just the most reliable way to get mob bugged so that it doesn't attack you, health resets to full non-stop and you are kept in combat forever (https://github.com/SallyWhitemane/Maelstrom/issues/29). However, after playing the game now for a while I don't think stealth is really the issue, it's just that something causes mobs to get bugged (autoattacks from stealth being most obvious). What the exact conditions to get the mob bugged are, that I don't know, but to me it seems to be issue beyond autoattacking from stealth.

What I think, after seeing all these reports about mobs getting bugged and resetting health to full, is that it must just be some generic issue with the mobs evading or whatever it is that causes them to be bugged. At least the following issues all share somewhat similar behaviour of the bugged mobs (resetting hp to full, not attacking, keeping you in combat):
- this issue
- https://github.com/SallyWhitemane/Maelstrom/issues/30
- https://github.com/SallyWhitemane/Maelstrom/issues/15
- https://github.com/SallyWhitemane/Maelstrom/issues/16
- https://github.com/SallyWhitemane/Maelstrom/issues/24
- https://github.com/SallyWhitemane/Maelstrom/issues/41

This could also be the case in the reported critter issue (https://github.com/SallyWhitemane/Maelstrom/issues/5) but can't login to test that now.

**Comment by ghost** [comment] 2022-06-06 15:06
@phonkala Please, retest it when you have time.

**Comment by phonkala** [comment] 2022-06-06 15:33
The issue of autoattacks done in stealth always make the target bugged (https://github.com/SallyWhitemane/Maelstrom/issues/29) seems to be now resolved in most cases, including https://github.com/SallyWhitemane/Maelstrom/issues/24 (closed it myself as it was mine originally).

However, Foe Reaper 5000 https://github.com/SallyWhitemane/Maelstrom/issues/41 still remains bugged.

About this specific issue (Pygmy Surf Crawler) or the others I personally didn't report, I can not say as I didn't have this issue.

**Comment by ghost** [comment] 2022-06-06 15:44
Alright. I will wait for the authors.
Thanks.

**Comment by ghost** [comment] 2022-06-07 07:45
I believe it's fixed.

**Closed as completed by ghost** 2022-06-07 07:45 UTC
Labels: help wanted
