### ISSUE TITLE
Dungeon: Deadmines - Cata Server Maelstorm

### ISSUE THREAD

**Issue by Arkasus11** [SallyWhitemane/Maelstrom#94] opened 2022-06-11 09:04 UTC
By Testing Dungeons i See Deadmines is bugged.

1st - The Quests cant start from begin, the quest giver is at the end of the Dungeon, and gives all Quests "Lieutnant Harolio Laine"

2nd - The Endboss "Captain Cookie" is bugged and unkillable + can Fly

Cata Server - Maelstorm PTR

**Comment by phonkala** [comment] 2022-06-11 09:53
I was actually wondering about the quests too, confirmed that part being bugged with this video: https://www.youtube.com/watch?v=UWSOU2yPPS8&t=85s

So yea first quest should be available right at start, and they should get completed when killing the correct boss, and new quest should pop up. Currently, like Arkasus said, all quests are only available at last boss (ship deck) so you kinda need two runs in Deadmines to complete those.

Cookie should be fixed but it's not live on the server yet. It was reported already and the issue is closed so now we wait :)

**Closed as completed** 2022-06-12 21:19 UTC
