### ISSUE TITLE
[NPC] Volchan animation bug + won't aggro upon being attacked

### ISSUE THREAD

**Issue by ghost** [SallyWhitemane/Maelstrom#125] opened 2022-06-14 19:26 UTC
**Description:**
Wowhead: https://www.wowhead.com/npc=10119/volchan#comments

Volchan has janky swimming animation above the lava and won't aggro upon being attacked, locking attacker in combat. See vid below

https://user-images.githubusercontent.com/106853563/173672150-21c6f8d7-9bb0-4e91-b6b7-cfbdc516360c.mp4

**How to reproduce:**
- Go to Volchan's patrol area in Burning Steppes
- Attack him
- He continues patrolling

**How it should work:**
Attacking him should cause him to aggro like any mob would.

**Comment by phonkala** [comment] 2022-06-15 07:44
Same problem, also keeps resetting it's hp to full non-stop.

![WoWScrnShot_061522_104420](https://user-images.githubusercontent.com/43609330/173771548-64259eeb-2ef7-44d3-89fa-4dbbd8d3ac24.jpg)

**Comment by UltraNix** [comment] 2022-06-16 09:49
Duplicate of #118

**Comment by phonkala** [comment] 2022-06-16 14:05
Also in our Discord someone reported that he had this same problem with the NPC "Brack".

"you cant kill him he get insta full life back and keep moving"

So it keeps happening quite randomly as someone else stated he had no problems with Brack.

**Closed as completed** 2022-06-16 20:17 UTC
